<div id="about-box-1"> 
<div id="about-box-1-in1">
<h5>Know Us</h5>
<p>
We are a bunch of buds who live in a fancy of sentiments. We are working with volunteers and love creating awesome and real connections.
</p><p>
We also enjoy good food, sound sleeps, great friends, memorable smiles and a working sense of possibilities + exploring convictions.
</p>
<h5>We Do Good Stuff</h5>
</div>
<div id="about-box-1-in2">
<div id="count-box-wrap"><div id="count-box"><div id="pre-count"><h2>Our teams operate currently</h2></div><div id="count-to"><div id="box-pre"><h3>in</h3></div><div id="box-mid"><h1><b class="timer" id="loca" data-from="0" data-to="23" data-speed="2000"></b></h1></div><div id="box-next"><h3>localities</h3></div></div>&nbsp;&nbsp;&nbsp;<div id="count-to"><div id="box-pre"><h3>with</h3></div><div id="box-mid"><h1><b class="timer" id="volunt" data-from="0" data-to="168" data-speed="3000"></b></h1></div><div id="box-next"><h3>volunteers</h3></div></div></div></div><script type="text/javascript">jQuery(function(o){function t(t){var n=o(this);t=o.extend({},t||{},n.data("countToOptions")||{}),n.countTo(t)}o("#volunt").data("countToOptions",{onComplete:function(o){t.call(this,{from:o,to:174,speed:3500})}}),o("#loca").data("countToOptions",{onComplete:function(o){t.call(this,{from:o,to:28,speed:3500})}}),o(".timer").each(t)});</script>

</div>
	<hr id="hrtype1">
</div>
<div id="about-box-2">
<div id="thoughts-container"><div id="thoughts-wrap"><ul class="bxslider"><li><div id="thought-box"><div id="thought-author"><img class="flip" src="images/Coco-Chanel.png" alt="?"></div><div id="thought-details"><p id="details-author">Coco Chanel<br><span> - French fashion designer</span></p><blockquote><p> Some people think luxury is the opposite of poverty. It is not. It is the opposite of vulgarity.</p></blockquote></div></div></li><li><div id="thought-box"><div id="thought-author"><img class="flip" src="images/Bill-Gates.png" alt="?"></div><div id="thought-details"><p id="details-author">Bill Gates <br><span> - Business magnate and philanthropist</span></p><blockquote><p> I believe that if you show people the problems and you show them the solutions they will be moved to act.</p></blockquote></div></div></li><li><div id="thought-box"><div id="thought-author"><img class="flip" src="images/Edmund-Burke.png" alt="?"></div><div id="thought-details"><p id="details-author"> Edmund Burke<br><span> - Author and philosopher</span></p><blockquote><p> The only thing necessary for the triumph of evil is for good people to do nothing.</p></blockquote></div></div></li><li><div id="thought-box"><div id="thought-author"><img class="flip" src="images/Martin-Luther-King-Jr.png" alt="?"></div><div id="thought-details"><p id="details-author">Martin Luther King, Jr.<br><span> - Baptist minister and civil rights activist</span></p><blockquote><p>Our lives begin to end the day we become silent about things that matter.</p></blockquote></div></div></li><li><div id="thought-box"><div id="thought-author"><img class="flip" src="images/Buchman-Frank.png" alt="?"></div><div id="thought-details"><p id="details-author">Frank Buchman<br><span> - Protestant evangelist </span></p><blockquote><p> There is enough in the world for everyone's need, but not for everyone's greed.</p></blockquote></div></div></li><li><div id="thought-box"><div id="thought-author"><img class="flip" src="images/Nelson-Mandela.png" alt="?"></div><div id="thought-details"><p id="details-author">Nelson Mandela<br><span> - Former President of South Africa</span></p><blockquote><p> As long as poverty, injustice and gross inequality exist in our world, none of us can truly rest. </p></blockquote></div></div></li></ul></div></div><script type="text/javascript">$(document).ready(function(){$(".bxslider").bxSlider({mode:"fade",auto:!0,autoDirection:"prev",randomStart:!0,pager:!1,pause:8e3,autoHover:!0,autoDelay:5e3,onSlideBefore:function(){var e=.35,t=0;t+=180,$(".flip").css("transform","rotateY("+t+"deg)").css("transition","all "+e+"s ease-in-out")},onSlideAfter:function(){var e=.8,t=0;t-=180,$(".flip").css("transform","rotateY("+t+"deg)").css("transition","all "+e+"s ease-in-out")}})});</script>
</div>
