<?php    opcache_reset();  date_default_timezone_set('Asia/Calcutta');$today = time(); $t = date('Y-m-d' , $today); require('../db/init.php');$email_mode = 'false';$email_mode=Sanitize($_POST['cb']);$lid = Sanitize($_POST['id']);$lid1=$lid;$lid =substr($lid,14);$userData['userId'];$pic=Sanitize($_POST['pic']); $fols=Sanitize($_POST['fols']);$maincampline = handle_data($_POST['maincampline']);  $camptext1 = handle_data($_POST['camptext']); $camptext = $camptext1;     /*$camptext=str_replace('<div>','99x8bec',$camptext);$camptext=str_replace('</div>','77x8bec',$camptext);$camptext=str_replace('<br>','99c8bex',$camptext); $camptext=str_replace('<p>','99x8bec',$camptext);$camptext=str_replace('</p>','77x8bec',$camptext); *//*$camptext1=str_replace('</b>','<br style="margin-top:20px;margin-bottom:20px">',$camptext); $camptext1=str_replace('</span>','<br style="margin-top:20px;margin-bottom:20px">',$camptext1); $camptext1=str_replace('</li>','<br style="margin-top:20px;margin-bottom:20px">',$camptext1); $camptext1=str_replace('</ul>','<br style="margin-top:20px;margin-bottom:20px">',$camptext1); $camptext1=str_replace('</a>','<br style="margin-top:20px;margin-bottom:20px">',$camptext1); $camptext1=strip_tags($camptext1);$camptext1 = htmlentities($camptext1); $camptext1 =  utf8_decode(html_entity_decode($camptext1));$camptext1=str_replace('?',' ',$camptext1);*/ /*$camptext=strip_tags($camptext);$camptext = htmlentities($camptext); $camptext =  utf8_decode(html_entity_decode($camptext));$camptext=str_replace('?',' ',$camptext);  $camptext1=str_replace('99x8bec','	  <p style="Margin-top: 20px;Margin-bottom: 0;font-family: roboto,tahoma,sans-serif;"><span class="font-roboto">',$camptext);   $camptext1=str_replace('77x8bec','</span></p>',$camptext1); $camptext1=str_replace('99c8bex','<br style="margin-top:20px;margin-bottom:20px">',$camptext1); $camptext=str_replace('<div>','99x8bec',$camptext);$camptext=str_replace('</div>','77x8bec',$camptext);$camptext=Sanitize($camptext);$camptext=str_replace('99x8bec','<p>',$camptext);$camptext=str_replace('77x8bec','</p>',$camptext); $camptext=str_replace('99c8bex','<br>',$camptext); *///Preserve <div> tag   
//get array methodif(empty($camptext) || empty($maincampline)){	echo 'Please leave no fields empty.';	exit();}  $chk = mysqli_query($GLOBALS['conn'],"SELECT * FROM camps WHERE mainline = '$maincampline' AND source_user = '$u' AND date = '$t'");$n = mysqli_num_rows($chk);if($n > 0){	echo 3; 	exit();} 
$supporters = explode(",", $fols);  
$checkedsize = sizeof($supporters);
if($checkedsize > 0){  $camp = mysqli_query($GLOBALS['conn'],"Insert into camps (mainline,text,pic,date,source_user,num_target) VALUES ('$maincampline','$camptext','$pic','$t','$u','$checkedsize')");	  $check = mysqli_query($GLOBALS['conn'],"SELECT campId FROM camps WHERE mainline = '$maincampline' AND source_user = '$u' AND date = '$t'");$n = mysqli_num_rows($check);   if($n == 1){	$r=mysqli_fetch_assoc($check);		$campId=$r['campId'];		$mail_ids = [];		for($i = 0 ; $i < $checkedsize ; $i++){  				$temp = $supporters[$i];			$temp = substr($temp,9);                    			$temp = unsafe_($temp);                     			$temp = $temp-448;			$incl = mysqli_query($GLOBALS['conn'],"INSERT INTO camp_table (campId,targetId) VALUES ('$campId' ,'$temp')"); 			if($email_mode == 'yes'){	$q1 = mysqli_query($GLOBALS['conn'],"SELECT email FROM users WHERE userId = '$temp'");		$n1=mysqli_num_rows($q1);			if($n1 == 1){				$r1 = mysqli_fetch_assoc($q1);				$a1 = $r1['email'];			if(!empty($a1)){				$mail_ids[] = $a1; 			}		}	}else{}echo 1;		}  if($email_mode == 'yes'){	$a=null;	$b=null;	$c=null;	$q=mysqli_query($GLOBALS['conn'],"SELECT fName,lName,email FROM users WHERE userId='$u'");		$n=mysqli_num_rows($q);			if($n==1){				$r2=mysqli_fetch_assoc($q);				$a=$r2['email'];			$b=$r2['fName'];				$c=$r2['lName']; 			}			
$loadH=getHIT($lid);
$arr1=array('src="main','h1','h2','id="H_DIV_1"','id="H_SECTION_2"','id="H_UL_3"','id="H_LI_4"','id="H1_5"','id="FIGCAH_PTION_9"','id="FIGURE_6"','id="H_H2_7"','id="IMG_8"','id="H_UL_10"','id="H_LI_11"','id="H3_12"','id="H_LI_13"','id="H_LI_15"','id="H3_14"','id="H3_16"','id="H_DIV_17"','id="H_UL_18"','id="H_LI_19"','id="H_LI_20"','id="H_BR_21"','id="inline"','id="H_DIV_23"','id="H_DIV_26"','id="H_H2_24"','id="H_H2_27"','id="H_P_25"','id="H_P_28"','id="H_H_BUTTON_29"','id="H_DIV_30"','id="rtd"','id="H_DIV_31"','id="H_B_32"','class="frontcolor"','class="backcolor"');
  
$arr2=array(' src="http://daanvir.org/main','div','div',' id="H_DIV_1" style=" height: 679.797px!important;
    text-align: center!important;   
    width: 100%!important;
    perspective-origin: 504px 339.891px!important;
    transform-origin: 504px 339.891px!important;
    font: normal normal normal normal 16px / normal \"Times New Roman\"!important;" ',' id="H_SECTION_2" style="height: 649.797px!important;
    max-width: 100%!important;
    text-align: center!important;
    width: 100%!important;
    perspective-origin: 504px 339.891px!important;
    transform-origin: 504px 339.891px!important;
    font: normal normal normal normal 16px / normal \"Times New Roman\"!important;" ',' id="H_UL_3" style="bottom: 0px!important;
    color: rgb(255, 250, 250)!important;
    height: 649.797px!important;
    left: 0px!important;
    position: relative!important;
    right: 0px!important;
    text-align: center!important;
    top: 0px!important;
    width: 100%!important;
    column-rule-color: rgb(255, 250, 250)!important;
    perspective-origin: 488px 324.891px!important;
    transform-origin: 488px 324.891px!important;
    border: 2px solid #ef9797!important;
    font: normal normal normal normal 16px / normal Lato, Calibri, Arial, sans-serif!important;
    list-style: none outside none!important;
    margin: 0px!important;
    outline: rgb(255, 250, 250) none 0px!important;
    padding: 0px!important;" ',' id="H_LI_4" style="zoom:78.6%!important; 
    color: #0f1b34!important;
    cursor: pointer!important;
    height:575px!important; 
    padding: 2px 20px;
    position: relative!important; 
    text-align: center!important; 
	vertical-align:top!important;
    display: inline-block!important;
    margin:2% 2% 5% 0%!important; 
    width: 378px!important; 
    column-rule-color: rgb(255, 250, 250)!important;
    perspective-origin: 160px 292.469px!important;
    transform-origin: 160px 292.469px!important;
    border: 3px solid rgb(254, 126, 137)!important;
    font: normal normal normal normal 16px / normal Lato, Calibri, Arial, sans-serif!important;
    list-style: none outside none;border-radius: 3px!important;
    outline: rgb(255, 250, 250) none 0px!important;
    box-shadow:1px 1px 10px rgba(0,0,0,0.5),inset 0 0 5px rgba(255,255,255,0.6)!important;
    -moz-box-shadow:1px 1px 10px rgba(0,0,0,0.5),inset 0 0 5px rgba(255,255,255,0.6)!important;
    -webkit-box-shadow:1px 1px 10px rgba(0,0,0,0.5),inset 0 0 5px rgba(255,255,255,0.6)!important;    
	background-color: #fff!important;" ',' id="H1_5" style="color: #000!important;
    cursor: pointer!important;
    background-color: yellow;
    position: relative!important;
    height: 22px!important;
    text-align: center!important;
    column-rule-color: rgb(255, 250, 250)!important;
    perspective-origin: 160px 22.5px!important;
    transform-origin: 160px 22.5px!important;
    border: 0px none rgb(255, 250, 250)!important;
    border-radius:8px!important;
    font: normal normal bold normal 14x / normal Lato, Calibri, Arial, sans-serif!important;
    list-style: none outside none!important;
    margin: 0px!important;
    font-size: 15px!important;
    margin-top: 30px!important;
    outline: rgb(255, 250, 250) none 0px!important; 
    z-index:3!important;
    width:50%!important;" ',' id="FIGCAH_PTION_9" style="
    bottom: 0px!important;
    overflow: hidden!important;
    color: rgb(255, 250, 250)!important;
    cursor: pointer!important;
    height: 202px!important;
    left: 0px!important;
    position: relative!important;
    right: 0px!important;background-color: #fe7e89!important;
    text-align: center!important;
    top: 137px!important;
    width: 100%!important;
    column-rule-color: rgb(255, 250, 250)!important;
    perspective-origin: 160px 155px!important;
    transform-origin: 160px 155px!important;
    border: 0px none rgb(255, 250, 250)!important;
    font: normal normal normal normal 16px / normal Lato, Calibri, Arial, sans-serif!important;
    list-style: none outside none!important;
    outline: rgb(255, 250, 250) none 0px!important;
    padding: 0px 0px 0px 0px!important;" ',' id="FIGURE_6" style="overflow: hidden;
	-moz-box-shadow: 0 4px 2px -3px!important;
	-webkit-box-shadow: 0 4px 2px -3px!important;
	box-shadow: 0 4px 2px -3px!important;
    color: rgb(255, 250, 250)!important;
    position: relative!important;
    cursor: pointer!important;
    height: auto!important;
    max-height: 35%!important;
    text-align: center!important;
    width: 100%!important;
    column-rule-color: rgb(255, 250, 250)!important;
    perspective-origin: 153.5px 113.375px!important;
    transform-origin: 153.5px 113.375px!important;
    background-color: #fff!important;
    border: 0px none rgb(255, 250, 250)!important;
    font: normal normal normal normal 16px / normal Lato, Calibri, Arial, sans-serif!important;
    list-style: none outside none!important;
    margin: 0!important;
    position:relative!important;
    top:-325px!important;
    outline: rgb(255, 250, 250) none 0px!important;
    padding: 0!important;
    transition: opacity 0.2s ease 0s!important;
    z-index:1!important;" ',' id="H_H2_7" style="
    display:none;color: #5bc2ce!important;
    cursor: pointer!important;
    height: 24px!important;
    text-align: center!important;
    width: 288px!important;
    width: 100%!important;
    column-rule-color: #5bc2ce!important;
    perspective-origin: 144px 19px!important;
    transform-origin: 144px 19px!important;
    border: 0px none #5bc2ce!important;
    font: normal normal bold normal 18px / normal Lato, Calibri, Arial, sans-serif!important;
    list-style: none outside none!important;
    margin: 0px!important;
    outline: #5bc2ce none 0px!important;
    padding: 10px 0px 8px 0!important;
    background-color: #edecec!important;" ',' id="IMG_8" style="color: rgb(255, 250, 250)!important;
    cursor: pointer!important;
    display: block!important;
	position: absolute!important;
    top: 0px!important;     
    text-align: center!important;
    width: 100%!important;
    column-rule-color: rgb(255, 250, 250)!important;
    perspective-origin: 144.109px 84.375px!important;
    transform-origin: 144.109px 84.375px!important;
    border: 0px none rgb(255, 250, 250)!important;
    font: normal normal normal normal 16px / normal Lato, Calibri, Arial, sans-serif!important;
    list-style: none outside none!important;
    outline: rgb(255, 250, 250) none 0px!important;
    padding: 0!important;
    position: relative!important;
    z-index: 2!important;" ',' id="H_UL_10" style=" bottom: 0px!important;
    color: rgb(255, 250, 250)!important;
    cursor: pointer!important;
    height: 40px!important;
    left: 0px!important;
    position: relative!important;
    right: 0px!important;
    text-align: center!important;
    top: 0px!important;
    width: 100%!important;
    column-rule-color: rgb(255, 250, 250)!important;
    perspective-origin: 154.016px 20px!important;
    transform-origin: 154.016px 20px!important;
    border: 0px none rgb(255, 250, 250)!important;
    font: normal normal normal normal 16px / normal Lato, Calibri, Arial, sans-serif!important;
    list-style: none outside none!important;
    margin: 0px 0px 0px 0px!important;
    outline: rgb(255, 250, 250) none 0px!important;
    padding: 0px!important;
    background-color: #fff!important;" ',' id="H_LI_11" style="bottom: -2px!important;
    color: rgb(51, 102, 102)!important;
    cursor: pointer!important;
    float: left!important;
    height: 25px!important;
    left: 0px!important;
    position: relative!important;
    right: 0px!important;
    text-align: center!important;
    top: 2px!important;
    vertical-align: middle!important;
    width: 102px!important;
    column-rule-color: rgb(51, 102, 102)!important;
    perspective-origin: 51px 18.5px!important;
    transform-origin: 51px 18.5px!important;
    border: 0px none rgb(51, 102, 102)!important;
    font: normal normal normal normal 16px / normal Lato, Calibri, Arial, sans-serif!important;
    list-style: none outside none!important;
    outline: rgb(51, 102, 102) none 0px!important;
    padding: 6px!important;" ',' id="H3_12" style="color: #fe7e8f!important;
    cursor: pointer!important;
    height: 22px!important;
    text-align: left!important;
    width: 81px!important;
    column-rule-color: rgb(255, 255, 255)!important;
    perspective-origin: 45px 13px!important;
    transform-: 45px 13px!important;
    border: 0px none rgb(255, 255, 255)!important;
    font: normal normal bold normal 18px / normal Lato, Calibri, Arial, sans-serif!important;
    list-style: none outside none!important;
    margin: 0px!important;
    outline: rgb(255, 255, 255) none 0px!important;
    padding: 2px 2px 2px 7px!important;" ',' id="H_LI_13" style="bottom: -2px!important;
    color: rgb(51, 102, 102)!important;
    cursor: pointer!important;
    float: left!important;
    height: 25px!important;
    left: 0px!important;
    position: relative!important;
    right: 0px!important;
    text-align: center!important;
    top: 2px!important;
    vertical-align: middle!important;
    width: 90.57px!important;
    column-rule-color: rgb(51, 102, 102)!important;
    perspective-origin: 51px 18.5px!important;
    transform-origin: 51px 18.5px!important;
    background-color:#f5f5f5!important;
    font: normal normal normal normal 16px / normal Lato, Calibri, Arial, sans-serif!important;
    list-style: none outside none!important;
    padding: 6px!important;" ',' id="H_LI_15" style="bottom: -2px!important;
    color: rgb(51, 102, 102)!important;
    cursor: pointer!important;
    float: left!important;
    height: 25px!important;
    left: 0px!important;
    position: relative!important;
    right: 0px!important;
    text-align: center!important;
    top: 2px!important;
    vertical-align: middle!important;
    width: 90.57px!important;
    column-rule-color: rgb(51, 102, 102)!important;
    perspective-origin: 51px 18.5px!important;
    transform-origin: 51px 18.5px!important;
    background-color:#f5f5f5!important;
    font: normal normal normal normal 16px / normal Lato, Calibri, Arial, sans-serif!important;
    list-style: none outside none!important;
    padding: 6px!important;" ',' id="H3_14" style="cursor: pointer!important;
    height: 22px!important;
    text-align: left!important;
    width: 81px!important;
    column-rule-color: rgb(51, 102, 102)!important;
    perspective-origin: 45px 13px!important;
    transform-origin: 45px 13px!important;
    border: 0px none rgb(51, 102, 102)!important;
    font: normal normal bold normal 16px / normal Lato, Calibri, Arial, sans-serif!important;
    list-style: none outside none!important;
    margin: 0px!important;
    outline: rgb(51, 102, 102) none 0px!important;
    padding: 2px 2px 2px 7px!important;" ',' id="H3_16" style="cursor: pointer!important;
    height: 22px!important;
    text-align: left!important;
    width: 84px!important;
    column-rule-color: rgb(51, 102, 102)!important;
    perspective-origin: 45px 13px!important;
    transform-origin: 45px 13px!important;
    border: 0px none rgb(51, 102, 102)!important;
    font: normal normal bold normal 16px / normal Lato, Calibri, Arial, sans-serif!important;
    list-style: none outside none!important;
    margin: 0px!important;
    outline: rgb(51, 102, 102) none 0px!important;
    padding: 2px 2px 2px 7px!important;" ',' id="H_DIV_17" style="overflow: hidden!important;
    overflow-y: auto!important;
    background-color: #fff!important;
    bottom: 0px!important;
    color: rgb(255, 250, 250)!important;
    cursor: pointer!important;
    height: 145px!important;
    left: 0px!important;
    position: relative!important;
    right: 0px!important;
    text-align: center!important;
    top: 0px!important;
    width: 90%!important;
    padding: 5%!important;
    padding-bottom: 0!important;
    column-rule-color: rgb(255, 250, 250)!important;
    perspective-origin: 153.859px 72.5px!important;
    transform-origin: 153.859px 72.5px!important;
    border: 0px none rgb(255, 250, 250)!important;
    font: normal normal normal normal 16px / normal Lato, Calibri, Arial, sans-serif!important;
    list-style: none outside none!important;
    outline: rgb(255, 250, 250) none 0px!important;" ',' id="H_UL_18" style="bottom: 0px!important;
    color: rgb(255, 250, 250)!important;
    cursor: pointer!important;
    left: 0px!important;
    position: relative!important;
    right: 0px!important;
    text-align: center!important;
    top: 0px!important;
    width: 100%!important;
    column-rule-color: rgb(255, 250, 250)!important;
    perspective-origin: 155.125px 5px!important;
    transform-origin: 155.125px 5px!important;
    border: 0px none rgb(255, 250, 250)!important;
    font: normal normal normal normal 16px / normal Lato, Calibri, Arial, sans-serif!important;
    list-style: square outside none!important;
    margin: 0px 0px 0px 1px!important;
    outline: rgb(255, 250, 250) none 0px!important;
    padding: 0px 0px 0px 21px!important;" ',' id="H_LI_19" style="text-align: left!important;
    bottom: -2px!important;
    color: #404040!important;
    cursor: pointer!important;
    float: left!important; 
    left: 0px!important;
    position: relative!important;
    right: 0px!important;
    top: 2px!important;
    vertical-align: middle!important;
    width: 90%!important;
    column-rule-color: rgb(255, 255, 255)!important;
    perspective-origin: 144.828px 25px!important;
    transform-origin: 144.828px 25px!important;
    border: 0px none rgb(255, 255, 255)!important;
    font: normal normal normal normal 17px / normal Lato, Calibri, Arial, sans-serif!important;
    list-style: square outside none!important;
    outline: rgb(255, 255, 255) none 0px!important;
    padding: 6px!important;" ',' id="H_LI_20" style="text-align: left!important;
    bottom: -2px!important;
    color:#494949!important;
    cursor: pointer!important;
    float: left!important; 
    left: 0px!important;
    position: relative!important;
    right: 0px!important;
    top: 2px!important;
    vertical-align: middle!important;
    width: 90%!important;
    column-rule-color: rgb(255, 255, 255)!important;
    perspective-origin: 144.828px 15.5px!important;
    transform-origin: 144.828px 15.5px!important;
    border: 0px none rgb(255, 255, 255)!important;
    font: normal normal normal normal 16px / normal Lato, Calibri, Arial, sans-serif!important;
    list-style: square outside none!important;
    outline: rgb(255, 255, 255) none 0px!important;
    padding: 6px!important;" ',' id="H_BR_21" style="color: rgb(255, 250, 250)!important;
    cursor: pointer!important;
    text-align: center!important;
    column-rule-color: rgb(255, 250, 250)!important;
    border: 0px none rgb(255, 250, 250)!important;
    font: normal normal normal normal 16px / normal Lato, Calibri, Arial, sans-serif!important;
    list-style: none outside none!important;
    outline: rgb(255, 250, 250) none 0px!important;" ',' id="inline" style=" 
	display:none!important;
    bottom: -20px!important;
    position: relative;
    height: 14px!important;
    width: calc( 100% - 30px)!important; 
    border-left: 15px solid #fff!important;
    border-right: 15px solid #fff!important; 
    background-color: #fff!important;" ',' id="H_DIV_23" style=" 
    display: inline-block!important;
    float: left!important;
	clear:both;
    height: 42px!important;
    text-align: center!important;
    width: 45%!important;
    font-size: 15px!important;
    column-rule-color: rgb(255, 250, 250)!important;
    perspective-origin: 69.5px 34px!important;
    transform-origin: 69.5px 34px!important; 
    border: 0px none rgb(255, 250, 250);
    font: normal normal normal normal 16px / normal Lato, Calibri, Arial, sans-serif!important;
    list-style: none outside none!important;
    margin: 0!important;
    outline: rgb(255, 250, 250) none 0px!important;
    padding: 4px 8px 5px 3px!important;
    top:18px!important;
    left:-10%!important;" ',' id="H_DIV_26" style="position: relative!important;
    color: #0e0e0e!important;
    cursor: pointer!important;
    display: inline-block!important;
    float: left!important;
    height: 42px!important;
    text-align: center!important;
    width: 45%!important;
    column-rule-color: rgb(255, 250, 250)!important;
    perspective-origin: 69.5px 34px!important;
    transform-origin: 69.5px 34px!important;
    background: url(\"/images/transparent.png\")!important;
    border: 0px none rgb(255, 250, 250)!important;
    font: normal normal normal normal 16px / normal Lato, Calibri, Arial, sans-serif!important;
    list-style: none outside none!important;
    margin: 0!important;
    outline: rgb(255, 250, 250) none 0px!important;
    padding: 4px 8px 5px 3px!important;
    top:-30px!important;
    left:-60%!important;
    font-weight: bolder!important;" ',' id="H_H2_24" style="color: #333!important;
    cursor: pointer!important;
    height: 13px!important;
    text-align: center!important;
    width: 119px!important;
    column-rule-color: rgb(51, 102, 102)!important;
    perspective-origin: 64px 13px!important;
    transform-origin: 64px 13px!important;
    border: 0px none rgb(51, 102, 102)!important;
    font: normal normal bold normal 15px / normal Lato, Calibri, Arial, sans-serif!important;
    list-style: none outside none!important;
    margin: 0px!important;
    font-size: 13px!important;
    outline: rgb(51, 102, 102) none 0px!important;
    padding: 90px 1px 6px 4px!important;
    font-weight: normal!important;" ',' id="H_H2_27" style="color: #333!important;
    cursor: pointer!important;
    height: 13px!important;
    text-align: center!important;
    width: 119px!important;
    column-rule-color: rgb(51, 102, 102)!important;
    perspective-origin: 64px 13px!important;
    transform-origin: 64px 13px!important;
    border: 0px none rgb(51, 102, 102)!important;
    font: normal normal bold normal 15px / normal Lato, Calibri, Arial, sans-serif!important;
    list-style: none outside none!important; 
    margin-left: 60%!important;  
    padding: 0px 1px 1px 4px!important;
    font-size: 13px!important;
    outline: rgb(51, 102, 102) none 0px!important; 
    font-weight: normal!important;  
	margin-top: -15%!important;" ',' id="H_P_25" style="color: #161616!important;
    cursor: pointer!important;
    height: 31px!important;
    text-align: center!important;
    width: 116px!important;
    column-rule-color: #5bc2ce!important;
    perspective-origin: 64px 17.5px!important;
    transform-origin: 64px 17.5px!important;
    border: 0px none #5bc2ce!important;
    font: normal normal normal normal 20px / normal Lato, Calibri, Arial, sans-serif!important;
    list-style: none outside none!important;
    margin: 0px!important;
    font-size: 18px!important;
    outline: #5bc2ce none 0px!important;
    padding: 1px 1px 1px 5px!important;" ',' id="H_P_28" style="color: #161616!important;
    cursor: pointer!important;
    height: 31px!important;
    text-align: center!important;
    width: 116px!important;
    column-rule-color: #5bc2ce!important;
    perspective-origin: 64px 17.5px!important;
    transform-origin: 64px 17.5px!important;
    border: 0px none #5bc2ce!important;
    font: normal normal normal normal 20px / normal Lato, Calibri, Arial, sans-serif!important;
    list-style: none outside none!important;
    margin: 0px!important;
    font-size: 18px!important;
    outline: #5bc2ce none 0px!important;padding: 7px 1px 1px 5px!important;
    margin-left: 60%!important;
    font-weight: bold!important;" ',' id="H_H_BUTTON_29" style="border-radius: 3px!important;
    font-weight: 700!important;
    bottom: 2px!important;
    color: #f8f8f8!important;
    display: block!important;
    height: 45px!important;
    left: 10%!important; 
    position: absolute!important; 
    bottom: -45px!important;margin-left: -1px;
    width: 101%!important;
    column-rule-color: rgb(255, 255, 255)!important;
    perspective-origin: 151.5px 22.5px!important;
    transform-origin: 151.5px 22.5px!important;
    border: 0px solid #efefef!important;
    background-color: #404040!important; 
    font: normal normal normal normal 16px / normal Arial!important;
    list-style: none outside none!important;
    outline: rgb(255, 255, 255) none 0px!important;" ',' id="H_DIV_30" style=" bottom: 0px!important;
    color: rgb(255, 250, 250)!important;display: none;
    cursor: pointer!important;
    height: 280px!important;
    left: 150px!important;
    position: absolute!important;
    text-align: center!important;
    top: 358px!important;
    border-radius:5px!important;
    width: 8px!important; 
    background-color:#E7E7E7!important;
    border: 0px none rgb(255, 250, 250)!important;
    font: normal normal normal normal 16px / normal Lato, Calibri, Arial, sans-serif!important;
    list-style: none outside none!important;
    border-left: none!important;
    transform: rotate(90deg)!important;" ',' id="rtd" style="transform: rotate(-90deg)!important;
    margin-left: -23px!important;
    margin-top: 2px!important;" ',' id="H_DIV_31" style="bottom: 0px!important;
    color: rgb(255, 250, 250)!important;
    cursor: pointer!important;
    height: 332.625px!important;
    left: 0px!important;
    position: absolute!important;
    right: 0px!important;
    text-align: center!important; 
    width: 8px!important;
    column-rule-color: rgb(255, 250, 250)!important;
    perspective-origin: 7.5px 166.313px!important;
    transform-origin: 7.5px 166.313px!important;
    background-color:#FAE00D!important;
	border: 0px none rgb(255, 250, 250)!important;
    border-radius:5px!important;
    font: normal normal normal normal 16px / normal Lato, Calibri, Arial, sans-serif!important;
    list-style: none outside none!important;
    outline: rgb(255, 250, 250) none 0px!important;" ',' id="H_B_32" style="color: #858585!important;
    cursor: pointer!important;
    text-align: center!important;
    column-rule-color: rgb(255, 255, 255)!important;
    background-color: none!important;
    border: 0px none rgb(255, 255, 255)!important;
    font: normal normal bold normal 16px / normal Lato, Calibri, Arial, sans-serif!important;
    list-style: none outside none!important;
    outline: rgb(255, 255, 255) none 0px!important;
    padding: 0 10px 0 0!important;" ',' class="frontcolor" style="
	background-color:#fff!important; " ',' class="backcolor" style="
    background-color: #dedddd!important; " ');
$loadH = str_replace($arr1,$arr2,$loadH);
$email_data='<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><!--[if IE]><html xmlns="http://www.w3.org/1999/xhtml" class="ie"><![endif]--><!--[if !IE]><!--><html style="margin: 0;padding: 0;" xmlns="http://www.w3.org/1999/xhtml"><!--<![endif]--><head>    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">    <title></title>    <!--[if !mso]><!--><meta http-equiv="X-UA-Compatible" content="IE=edge"><!--<![endif]-->    <meta name="viewport" content="width=device-width">
<style type="text/css">
@media only screen and (min-width: 620px){.wrapper{min-width:600px !important}.wrapper h1{}.wrapper h1{font-size:26px !important;line-height:34px !important}.wrapper h2{}.wrapper h2{font-size:20px !important;line-height:28px !important}.wrapper h3{}.column p,.column ol,.column ul{}.wrapper .size-8{font-size:8px !important;line-height:14px !important}.wrapper .size-9{font-size:9px !important;line-height:16px !important}.wrapper .size-10{font-size:10px !important;line-height:18px !important}.wrapper .size-11{font-size:11px !important;line-height:19px !important}.wrapper .size-12{font-size:12px !important;line-height:19px !important}.wrapper .size-13{font-size:13px !important;line-height:21px !important}.wrapper .size-14{font-size:14px !important;line-height:21px !important}.wrapper .size-15{font-size:15px !important;line-height:23px !important}.wrapper .size-16{font-size:16px !important;line-height:24px !important}.wrapper .size-17{font-size:17px !important;line-height:26px !important}.wrapper .size-18{font-size:18px !important;line-height:26px !important}.wrapper .size-20{font-size:20px !important;line-height:28px !important}.wrapper .size-22{font-size:22px !important;line-height:31px !important}.wrapper .size-24{font-size:24px !important;line-height:32px !important}.wrapper .size-26{font-size:26px !important;line-height:34px !important}.wrapper .size-28{font-size:28px !important;line-height:36px !important}.wrapper .size-30{font-size:30px !important;line-height:38px !important}.wrapper .size-32{font-size:32px !important;line-height:40px !important}.wrapper .size-34{font-size:34px !important;line-height:43px !important}.wrapper .size-36{font-size:36px !important;line-height:43px !important}.wrapper .size-40{font-size:40px !important;line-height:47px !important}.wrapper .size-44{font-size:44px !important;line-height:50px !important}.wrapper .size-48{font-size:48px !important;line-height:54px !important}.wrapper .size-56{font-size:56px !important;line-height:60px !important}.wrapper .size-64{font-size:64px !important;line-height:63px !important}}</style>    <style type="text/css">body {  margin: 0;  padding: 0;}table {  border-collapse: collapse;  table-layout: fixed;}* {  line-height: inherit;}[x-apple-data-detectors],[href^="tel"],[href^="sms"] {  color: inherit !important;  text-decoration: none !important;}.wrapper .footer__share-button a:hover,.wrapper .footer__share-button a:focus {  color: #ffffff !important;}.btn a:hover,.btn a:focus,.footer__share-button a:hover,.footer__share-button a:focus,.email-footer__links a:hover,.email-footer__links a:focus {  opacity: 0.8;}.preheader,.header,.layout,.column {  transition: width 0.25s ease-in-out, max-width 0.25s ease-in-out;}.layout,.header {  max-width: 400px !important;  -fallback-width: 95% !important;  width: calc(100% - 20px) !important;}div.preheader {  max-width: 360px !important;  -fallback-width: 90% !important;  width: calc(100% - 60px) !important;}.snippet,.webversion {  Float: none !important;}.column {  max-width: 400px !important;  width: 100% !important;}.fixed-width.has-border {  max-width: 402px !important;}.fixed-width.has-border .layout__inner {  box-sizing: border-box;}.snippet,.webversion {  width: 50% !important;}.ie .btn {  width: 100%;}.ie .column,[owa] .column,.ie .gutter,[owa] .gutter {  display: table-cell;  float: none !important;  vertical-align: top;}.ie div.preheader,[owa] div.preheader,.ie .email-footer,[owa] .email-footer {  max-width: 560px !important;  width: 560px !important;}.ie .snippet,[owa] .snippet,.ie .webversion,[owa] .webversion {  width: 280px !important;}.ie .header,[owa] .header,.ie .layout,[owa] .layout,.ie .one-col .column,[owa] .one-col .column {  max-width: 600px !important;  width: 600px !important;}.ie .fixed-width.has-border,[owa] .fixed-width.has-border,.ie .has-gutter.has-border,[owa] .has-gutter.has-border {  max-width: 602px !important;  width: 602px !important;}.ie .two-col .column,[owa] .two-col .column {  max-width: 300px !important;  width: 300px !important;}.ie .three-col .column,[owa] .three-col .column,.ie .narrow,[owa] .narrow {  max-width: 200px !important;  width: 200px !important;}.ie .wide,[owa] .wide {  width: 400px !important;}.ie .two-col.has-gutter .column,[owa] .two-col.x_has-gutter .column {  max-width: 290px !important;  width: 290px !important;}.ie .three-col.has-gutter .column,[owa] .three-col.x_has-gutter .column,.ie .has-gutter .narrow,[owa] .has-gutter .narrow {  max-width: 188px !important;  width: 188px !important;}.ie .has-gutter .wide,[owa] .has-gutter .wide {  max-width: 394px !important;  width: 394px !important;}.ie .two-col.has-gutter.has-border .column,[owa] .two-col.x_has-gutter.x_has-border .column {  max-width: 292px !important;  width: 292px !important;}.ie .three-col.has-gutter.has-border .column,[owa] .three-col.x_has-gutter.x_has-border .column,.ie .has-gutter.has-border .narrow,[owa] .has-gutter.x_has-border .narrow {  max-width: 190px !important;  width: 190px !important;}.ie .has-gutter.has-border .wide,[owa] .has-gutter.x_has-border .wide {  max-width: 396px !important;  width: 396px !important;}.ie .fixed-width .layout__inner {  border-left: 0 none white !important;  border-right: 0 none white !important;}.ie .layout__edges {  display: none;}.mso .layout__edges {  font-size: 0;}.layout-fixed-width,.mso .layout-full-width {  background-color: #ffffff;}@media only screen and (min-width: 620px) {  .column,  .gutter {    display: table-cell;    Float: none !important;    vertical-align: top;  }  div.preheader,  .email-footer {    max-width: 560px !important;    width: 560px !important;  }  .snippet,  .webversion {    width: 280px !important;  }  .header,  .layout,  .one-col .column {    max-width: 600px !important;    width: 600px !important;  }  .fixed-width.has-border,  .fixed-width.ecxhas-border,  .has-gutter.has-border,  .has-gutter.ecxhas-border {    max-width: 602px !important;    width: 602px !important;  }  .two-col .column {    max-width: 300px !important;    width: 300px !important;  }  .three-col .column,  .column.narrow {    max-width: 200px !important;    width: 200px !important;  }  .column.wide {    width: 400px !important;  }  .two-col.has-gutter .column,  .two-col.ecxhas-gutter .column {    max-width: 290px !important;    width: 290px !important;  }  .three-col.has-gutter .column,  .three-col.ecxhas-gutter .column,  .has-gutter .narrow {    max-width: 188px !important;    width: 188px !important;  }  .has-gutter .wide {    max-width: 394px !important;    width: 394px !important;  }  .two-col.has-gutter.has-border .column,  .two-col.ecxhas-gutter.ecxhas-border .column {    max-width: 292px !important;    width: 292px !important;  }  .three-col.has-gutter.has-border .column,  .three-col.ecxhas-gutter.ecxhas-border .column,  .has-gutter.has-border .narrow,  .has-gutter.ecxhas-border .narrow {    max-width: 190px !important;    width: 190px !important;  }  .has-gutter.has-border .wide,  .has-gutter.ecxhas-border .wide {    max-width: 396px !important;    width: 396px !important;  }} @media (max-width: 321px) {  .fixed-width.has-border .layout__inner {    border-width: 1px 0 !important;  }  .layout,  .column {    min-width: 320px !important;    width: 320px !important;  }  .border {    display: none;  }}.mso div {  border: 0 none white !important;}.mso .w560 .divider {  Margin-left: 260px !important;  Margin-right: 260px !important;}.mso .w360 .divider {  Margin-left: 160px !important;  Margin-right: 160px !important;}.mso .w260 .divider {  Margin-left: 110px !important;  Margin-right: 110px !important;}.mso .w160 .divider {  Margin-left: 60px !important;  Margin-right: 60px !important;}.mso .w354 .divider {  Margin-left: 157px !important;  Margin-right: 157px !important;}.mso .w250 .divider {  Margin-left: 105px !important;  Margin-right: 105px !important;}.mso .w148 .divider {  Margin-left: 54px !important;  Margin-right: 54px !important;}.mso .font-avenir,.mso .font-cabin,.mso .font-open-sans,.mso .font-ubuntu {  font-family: sans-serif !important;}.mso .font-bitter,.mso .font-merriweather,.mso .font-pt-serif {  font-family: Georgia, serif !important;}.mso .font-lato,.mso .font-roboto {  font-family: Tahoma, sans-serif !important;}.mso .font-pt-sans {  font-family: "Trebuchet MS", sans-serif !important;}.mso .footer__share-button p {  margin: 0;}.mso .size-8,.ie .size-8 {  font-size: 8px !important;  line-height: 14px !important;}.mso .size-9,.ie .size-9 {  font-size: 9px !important;  line-height: 16px !important;}.mso .size-10,.ie .size-10 {  font-size: 10px !important;  line-height: 18px !important;}.mso .size-11,.ie .size-11 {  font-size: 11px !important;  line-height: 19px !important;}.mso .size-12,.ie .size-12 {  font-size: 12px !important;  line-height: 19px !important;}.mso .size-13,.ie .size-13 {  font-size: 13px !important;  line-height: 21px !important;}.mso .size-14,.ie .size-14 {  font-size: 14px !important;  line-height: 21px !important;}.mso .size-15,.ie .size-15 {  font-size: 15px !important;  line-height: 23px !important;}.mso .size-16,.ie .size-16 {  font-size: 16px !important;  line-height: 24px !important;}.mso .size-17,.ie .size-17 {  font-size: 17px !important;  line-height: 26px !important;}.mso .size-18,.ie .size-18 {  font-size: 18px !important;  line-height: 26px !important;}.mso .size-20,.ie .size-20 {  font-size: 20px !important;  line-height: 28px !important;}.mso .size-22,.ie .size-22 {  font-size: 22px !important;  line-height: 31px !important;}.mso .size-24,.ie .size-24 {  font-size: 24px !important;  line-height: 32px !important;}.mso .size-26,.ie .size-26 {  font-size: 26px !important;  line-height: 34px !important;}.mso .size-28,.ie .size-28 {  font-size: 28px !important;  line-height: 36px !important;}.mso .size-30,.ie .size-30 {  font-size: 30px !important;  line-height: 38px !important;}.mso .size-32,.ie .size-32 {  font-size: 32px !important;  line-height: 40px !important;}.mso .size-34,.ie .size-34 {  font-size: 34px !important;  line-height: 43px !important;}.mso .size-36,.ie .size-36 {  font-size: 36px !important;  line-height: 43px !important;}.mso .size-40,.ie .size-40 {  font-size: 40px !important;  line-height: 47px !important;}.mso .size-44,.ie .size-44 {  font-size: 44px !important;  line-height: 50px !important;}.mso .size-48,.ie .size-48 {  font-size: 48px !important;  line-height: 54px !important;}.mso .size-56,.ie .size-56 {  font-size: 56px !important;  line-height: 60px !important;}.mso .size-64,.ie .size-64 {  font-size: 64px !important;  line-height: 63px !important;}.footer__share-button p {  margin: 0;}</style>      <!--[if !mso]><!--><style type="text/css">@import url(https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic|Roboto:400,700,400italic,700italic);</style><link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic|Roboto:400,700,400italic,700italic" rel="stylesheet" type="text/css"><!--<![endif]--><style type="text/css">body{background-color:#fbfbfb}.mso h1{}.mso h1{font-family:sans-serif !important}.mso h2{}.mso h3{}.mso .column,.mso .column__background td{}.mso .btn a{}.mso .webversion,.mso .snippet,.mso .layout-email-footer td,.mso .footer__share-button p{}.mso .logo{}.mso .logo{font-family:sans-serif !important}.logo a:hover,.logo a:focus{color:#1e2e3b !important}.mso .layout-has-border{border-top:1px solid #c8c8c8;border-bottom:1px solid #c8c8c8}.mso .layout-has-bottom-border{border-bottom:1px solid #c8c8c8}.mso .border,.ie .border{background-color:#c8c8c8}.mso h1,.ie h1{}.mso h1,.ie h1{font-size:26px !important;line-height:34px !important}.mso h2,.ie h2{}.mso h2,.ie h2{font-size:20px !important;line-height:28px !important}.mso h3,.ie h3{}.mso .layout__inner p,.ie .layout__inner p,.mso .layout__inner ol,.ie .layout__inner ol,.mso .layout__inner ul,.ie .layout__inner ul{}
</style>
<meta name="robots" content="noindex,nofollow"><meta property="og:title" content="'.$maincampline.'"></head><!--[if mso]>  <body class="mso"><![endif]--><!--[if !mso]><!-->  <body class="no-padding" style="margin: 0;padding: 0;-webkit-text-size-adjust: 100%;"><!--<![endif]-->    <table class="wrapper" style="border-collapse: collapse;table-layout: fixed;min-width: 320px;width: 100%;background-color: #fbfbfb;" cellpadding="0" cellspacing="0" role="presentation"><tbody><tr><td>      <div role="banner">                <div class="header" style="Margin: 0 auto;max-width: 600px;min-width: 320px; width: 320px;width: calc(28000% - 167400px);" id="emb-email-header-container">        <!--[if (mso)|(IE)]><table align="center" class="header" cellpadding="0" cellspacing="0" role="presentation"><tr><td style="width: 600px"><![endif]-->          <div class="logo emb-logo-margin-box" style="font-size: 26px;line-height: 32px;Margin-top: 6px;Margin-bottom: 16px;color: #41637e;font-family: Avenir,sans-serif;Margin-left: 20px;Margin-right: 20px;" align="center">            <div class="logo-left" align="left" id="emb-email-header"><a style="text-decoration: none;transition: opacity 0.1s ease-in;color: #41637e;" href="http://daanvir.org" target="_blank"><img style="display: block;height: auto;width: 100%;border: 0;max-width: 65px;" src="http://daanvir.org/main/images/pic.jpg" alt="Daanvir.org" width="65"></a></div>          </div>        <!--[if (mso)|(IE)]></td></tr></table><![endif]-->        </div>      </div>      <div role="section">      <div class="layout one-col fixed-width" style="Margin: 0 auto;max-width: 600px;min-width: 320px; width: 320px;width: calc(28000% - 167400px);overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;">        <div class="layout__inner" style="border-collapse: collapse;display: table;width: 100%;background-color: #ffffff;" emb-background-style="">        <!--[if (mso)|(IE)]><table align="center" cellpadding="0" cellspacing="0" role="presentation"><tr class="layout-fixed-width" emb-background-style><td style="width: 600px" class="w560"><![endif]-->          <div class="column" style="text-align: left;color: #565656;font-size: 14px;line-height: 21px;font-family: Georgia,serif;max-width: 600px;min-width: 320px; width: 320px;width: calc(28000% - 167400px);"> 		              <div style="min-height:150px;height:auto;padding: 24px;/* Margin-left: 20px; *//* Margin-right: 20px; */">      <h1 style="Margin-top: 0;Margin-bottom: 0;font-style: normal;font-weight: normal;color: #565656;font-size: 22px;line-height: 31px;font-family: lato,tahoma,sans-serif;"><span class="font-lato">'.$maincampline.'</span></h1><br><a href="http://daanvir.org/campaign.php?id1='.$lid1.'&id2=DONATION&id3=PAGE">'.$loadH.'</a><br style="margin-top:40px;height:40px"> <p style="Margin-top: 20px;Margin-bottom: 0;font-family: roboto,tahoma,sans-serif;"><span class="font-roboto">'.$camptext1.'</span></p> <p style="Margin-top: 20px;Margin-bottom: 0;font-family: roboto,tahoma,sans-serif;"><span class="font-roboto"><a href="http://daanvir.org">Login to see more..</a></span></p>       </div>                <div style="font-size: 12px;font-style: normal;font-weight: normal;" align="center">          <img class="gnd-corner-image gnd-corner-image-center gnd-corner-image-bottom" style="border: 0;display: block;height: auto;width: 100%;max-width: 900px;" alt="" width="600" src="http://daanvir.org/'.$pic.'">        </div>                </div>        <!--[if (mso)|(IE)]></td></tr></table><![endif]-->        </div>      </div>        <div style="line-height:20px;font-size:20px;">&nbsp;</div>        <div class="layout one-col fixed-width" style="Margin: 0 auto;max-width: 600px;min-width: 320px; width: 320px;width: calc(28000% - 167400px);overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;">        <div class="layout__inner" style="border-collapse: collapse;display: table;width: 100%;background-color: #ffffff;" emb-background-style="">        <!--[if (mso)|(IE)]><table align="center" cellpadding="0" cellspacing="0" role="presentation"><tr class="layout-fixed-width" emb-background-style><td style="width: 600px" class="w560"><![endif]-->          <div class="column" style="text-align: left;color: #565656;font-size: 14px;line-height: 21px;font-family: Georgia,serif;max-width: 600px;min-width: 320px; width: 320px;width: calc(28000% - 167400px);">                    <div style="Margin-left: 20px;Margin-right: 20px;">      <p style="padding: 24px;Margin-top: 0;Margin-bottom: 0;">- '.$b.' '.$c.'<br><strong>&nbsp; '.$a.'</strong></p>    </div>                  </div>        <!--[if (mso)|(IE)]></td></tr></table><![endif]-->        </div>      </div>        <div style="line-height:20px;font-size:20px;">&nbsp;</div>        <div class="layout one-col fixed-width" style="Margin: 0 auto;max-width: 600px;min-width: 320px; width: 320px;width: calc(28000% - 167400px);overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;">        <div class="layout__inner" style="border-collapse: collapse;display: table;width: 100%;background-color: #ffffff;" emb-background-style="">        <!--[if (mso)|(IE)]><table align="center" cellpadding="0" cellspacing="0" role="presentation"><tr class="layout-fixed-width" emb-background-style><td style="width: 600px" class="w560"><![endif]-->          <div class="column" style="text-align: left;color: #565656;font-size: 14px;line-height: 21px;font-family: Georgia,serif;max-width: 600px;min-width: 320px; width: 320px;width: calc(28000% - 167400px);">                    <div style="Margin-left: 20px;Margin-right: 20px;">      <div class="divider" style="display: block;font-size: 2px;line-height: 2px;Margin-left: auto;Margin-right: auto;width: 40px;background-color: #c8c8c8;">&nbsp;</div>    </div>                  </div>        <!--[if (mso)|(IE)]></td></tr></table><![endif]-->        </div>      </div>        <div style="line-height:20px;font-size:20px;">&nbsp;</div>              <div role="contentinfo">        <div class="layout email-footer" style="Margin: 0 auto;max-width: 600px;min-width: 320px; width: 320px;width: calc(28000% - 167400px);overflow-wrap: break-word;word-wrap: break-word;word-break: break-word;">          <div class="layout__inner" style="border-collapse: collapse;display: table;width: 100%;">          <!--[if (mso)|(IE)]><table align="center" cellpadding="0" cellspacing="0" role="presentation"><tr class="layout-email-footer"><td style="width: 400px;" valign="top" class="w360"><![endif]-->            <div class="column wide" style="text-align: left;font-size: 12px;line-height: 19px;color: #999;font-family: Georgia,serif;Float: left;max-width: 400px;min-width: 320px; width: 320px;width: calc(8000% - 47600px);">              <div style="Margin-left: 20px;Margin-right: 20px;Margin-top: 10px;Margin-bottom: 10px;">                <table class="email-footer__links emb-web-links" style="border-collapse: collapse;table-layout: fixed;" role="presentation"><tbody><tr role="navigation">                                </tr></tbody></table>                <div style="Margin-top: 20px;">                  <div>Daanvir.org</div>                </div>                <div style="Margin-top: 18px;">                  <div>This campaign was shared with you on Daanvir.org by '.$b.'. The complete campaign can be viewed in your inbox campaigns.</div>                  <div><a href="http://daanvir.org">Join today to be a part of social transformation</a></div>                </div>              </div>            </div>          <!--[if (mso)|(IE)]></td><td style="width: 200px;" valign="top" class="w160"><![endif]-->            <div class="column narrow" style="text-align: left;font-size: 12px;line-height: 19px;color: #999;font-family: Georgia,serif;Float: left;max-width: 320px;min-width: 200px; width: 320px;width: calc(72200px - 12000%);">              <div style="Margin-left: 20px;Margin-right: 20px;Margin-top: 10px;Margin-bottom: 10px;">                              </div>            </div>          <!--[if (mso)|(IE)]></td></tr></table><![endif]-->          </div>        </div>      </div>      <div style="line-height:40px;font-size:40px;">&nbsp;</div>    </div></td></tr></tbody></table> </body></html>';   include '../html/mailer.php';$mail->ClearAllRecipients();$mail->setFrom('noreply@daanvir.org', 'daanvir.org');$mail->addAddress('Daanvir.help@gmail.com', 'Daanvir');    $mail->Subject = $maincampline;$mail->isHTML(true); $mail->Body = $email_data; foreach ($mail_ids as $addr) {    $mail->addBCC($addr);}if(!$mail->send()){  echo 'Mail Error: ';}else { echo 1; }	}else{	echo 1;}	}else{	echo 'An unexpected error occurred. Please try again later.	Suggestion: You may reload the page and/ or change the title.'; 	exit();	}}else{	echo 'Please add supporters'; 	exit();}
?>